# Generated by Django 5.0.1 on 2024-03-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_transaction_order_transaction_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
